### PR TITLE
Proposed Swedish support for takeBreak function

### PR DESCRIPTION
**Pull request by sultan8**
This is a modification of takeBreak which adds support for Swedish. The new language parameter is optional with English as default. Fully backward compatible.

### CODE REVIEW

**Review by tfjaeger — CHANGES_REQUESTED** [review]
Nice job. This could work. However, to keep things parallel with how we do things elsewhere, I prefer not to handle this throw a language argument that leads to a hard-coded message but rather to give users the option to hand any arbitrary formatted string as argument takeBreakMessage.

**Review by tfjaeger — APPROVED** [review]
Nice, I think this will work better. We might have moved the default somewhere to the top of the function but I think this will do. I'll approve it now. Can you test and let me know if it works after updating your submodule?

**Comment by sultan8** [comment]
hi it does work (after pulling the latest JSEXP) when i run the experiment in my local environment.

**Comment by tfjaeger** [comment]
Thanks for letting me know, and on the server?

flo
________________________________
From: Maryann ***@***.***>
Sent: Sunday, December 3, 2023 2:39 PM
To: hlplab/JSEXP ***@***.***>
Cc: Jaeger, Florian ***@***.***>; State change ***@***.***>
Subject: [EXT] Re: [hlplab/JSEXP] Proposed Swedish support for takeBreak function (PR #1)


hi it does work when i run the experiment in my local environment.

**Pull request merged**
